version: '3'
services:
  nasm-gcc: 
    build: .
    working_dir: /usr/src
    volumes:
      - ./src:/usr/src
    command:
      - /bin/bash
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE
