version: "3"
services:
  nginx:
    image: nginx-simple:latest
    container_name: nginx-simple
    restart: always
    #    network_mode: "bridge"
    ports:
      - 9494:80
    volumes:
      - ./wwwroot/:/var/www/
    build:
      context: .
